### ISSUE TITLE
Code for the displaying data in the bootstrap elements

### ISSUE THREAD

**Issue by evlynmaria** [GroupMaria/ACSMS#113]
#109

**Comment by evlynmaria** [comment]
@phidza 

The following are the requirements:
1. Display the data in the quotation table in the table format .
as follows:

![image](https://cloud.githubusercontent.com/assets/8825075/6994331/e6dad262-dae3-11e4-8592-705b7e54cd19.png)

**Comment by evlynmaria** [comment]
Instead of the Order # , you need to use the Quotation # ,Quotation Date , Customer ID , Date Prepared.

**Comment by evlynmaria** [comment]
Please use the Quotation table for all the details. You need to create a simple jsp file and populate the data from the database.
Please find the details from the tutorial below:
http://javaknowledge.info/jstl-1-1-simple-insert-update-delete-example/

Here it clearly explains the step by step process for database related operation.

**Comment by evlynmaria** [comment]
Please don't do the bootstrap and formatting , just do the plain table . The related tasks are : #116 #112 

Once this task is completed , then these tasks can be completed easily.

**Comment by phidza** [comment]
Hi Maria I am trying to push the code for the bootstrap display and I am getting an error message  herewith is the error message and please advise 
Pushing to https://github.com/GroupMaria/ACSMS.git
To https://github.com/GroupMaria/ACSMS.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/GroupMaria/ACSMS.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by phidza** [comment]
Hi Maria I have pushed the code in Github please check it out and advise

**Comment by evlynmaria** [comment]
Please update your repository before pushing the changes. You have to get git bash and type git pull origin master. Let me review the changes , I will get back to you.

**Comment by phidza** [comment]
Checked in code
